### ISSUE TITLE
Can't type anything

### ISSUE THREAD

**Issue by ktmn** [garyxuehong/hyper-history#3]
```
Uncaught TypeError: Path must be a string. Received undefined
    assertPath @ path.js:7
    join @ path.js:466
    grepHistory @ C:\Users\User\.hyper_plugins\node_modules\hyper-history\index.js:176
    (anonymous function) @ C:\Users\User\.hyper_plugins\node_modules\hyper-history\index.js:128
    (anonymous function) @ C:\Users\User\.hyper_plugins\node_modules\hyperpower\index.js:27
    pe @ bundle.js:1
    (anonymous function) @ bundle.js:1
    onData @ bundle.js:41
    I.Terminal.onVTKeystroke @ bundle.js:47
    I.Keyboard.onKeyPress_ @ bundle.js:47
```

I have [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) installed so the idea was to run bash, which would have .bash_history, but I can't type anything due to this error not being handled.

**Comment by eosfelipe** [comment]
The same thing happened to me, I solved it by adding 
`const home = require('os).homedir()`
replace
`fs.readFile(path.join(process.env['HOME'], '.bash_history')`
for
`fs.readFile(path.join(home, '.bash_history')`
