### ISSUE TITLE
Dont work in 2.0-cannary

### ISSUE THREAD

**Issue by linonetwo** [garyxuehong/hyper-history#6]
2.0 canary, history will show up, but clicking result in nothing.

**Comment by linonetwo** [comment]
Is this project abandoned?

**Comment by garyxuehong** [comment]
Yep. I am happy to hand it over to someone else
lin onetwo <notifications@github.com>于2018年4月4日 周三下午1:41写道：

**Comment by linonetwo** [comment]
I would take it if you'd like. I will try to fix it in Qingming. This project is very useful for GUI users.

update April 18
I don't think I have the willpower to maintain this, shame on myself.

**Comment by linonetwo** [comment]
Works in stable channel 2.0. Closing this.
